"""Entity configuration."""

# Ship settings
SHIP_RADIUS = 15
SHIP_ACCELERATION = 200.0
SHIP_ROTATION_SPEED = 180.0
SHIP_MAX_SPEED = 300.0
SHIP_FRICTION = 0.99
SHIP_INVULNERABILITY_TIME = 3.0

# Weapon settings
BULLET_SPEED = 500.0
BULLET_LIFETIME = 1.0
FIRE_RATE = 0.25

# Asteroid settings
ASTEROID_SPEED_MIN = 50.0
ASTEROID_SPEED_MAX = 150.0
ASTEROID_ROTATION_MIN = 45.0
ASTEROID_ROTATION_MAX = 180.0
ASTEROID_SPLIT_SPEED_BOOST = 1.2

# Asteroid sizes
ASTEROID_LARGE_SIZE = 40
ASTEROID_MEDIUM_SIZE = 20
ASTEROID_SMALL_SIZE = 10
ASTEROID_SIZES = {
    "large": ASTEROID_LARGE_SIZE,
    "medium": ASTEROID_MEDIUM_SIZE,
    "small": ASTEROID_SMALL_SIZE
}

# Asteroid points
ASTEROID_LARGE_POINTS = 100
ASTEROID_MEDIUM_POINTS = 50
ASTEROID_SMALL_POINTS = 25

# Effect settings
THRUST_EFFECT_LIFETIME = 0.5
EXPLOSION_EFFECT_LIFETIME = 1.0
SPARKLE_EFFECT_LIFETIME = 0.3 