"""
Game constants package.
"""

from .ship import (
    SHIP_ACCELERATION, SHIP_MAX_SPEED, SHIP_ROTATION_SPEED,
    SHIP_FRICTION, SHIP_INVULNERABLE_TIME, SHIP_INITIAL_LIVES,
    SHIP_SHOOT_COOLDOWN
)
from .weapons import (
    BULLET_SPEED, BULLET_LIFETIME, BULLET_DAMAGE,
    BULLET_COOLDOWN, MAX_BULLETS
)
from .asteroids import (
    ASTEROID_SIZES, ASTEROID_POINTS, ASTEROID_RADIUS,
    ASTEROID_SPEED, ASTEROID_SPLIT_COUNT, MIN_ASTEROID_COUNT
)
from .particles import (
    PARTICLE_COLORS, EXPLOSION_PARTICLE_COUNT,
    EXPLOSION_PARTICLE_LIFETIME, EXPLOSION_PARTICLE_SPEED,
    THRUST_PARTICLE_COUNT, THRUST_PARTICLE_LIFETIME,
    THRUST_PARTICLE_SPEED
)
from .colors import (
    BLACK, WHITE, RED, GREEN, BLUE, YELLOW
)
from .display import (
    WINDOW_WIDTH, WINDOW_HEIGHT, WINDOW_TITLE, FPS,
    LAYER_BACKGROUND, LAYER_PARTICLES, LAYER_ASTEROIDS,
    LAYER_BULLETS, LAYER_PLAYER, LAYER_UI
)
from .game_settings import (
    MENU_FONT_SIZE, MENU_COLOR, MENU_HOVER_COLOR, MENU_SPACING,
    SOUND_VOLUME, MUSIC_VOLUME,
    ASSET_DIR, SPRITE_DIR, SOUND_DIR, MUSIC_DIR, FONT_DIR,
    STARTING_LIVES, SCORE_MULTIPLIER, HIGH_SCORE_COUNT
)

__all__ = (
    # Ship
    'SHIP_ACCELERATION', 'SHIP_MAX_SPEED', 'SHIP_ROTATION_SPEED',
    'SHIP_FRICTION', 'SHIP_INVULNERABLE_TIME', 'SHIP_INITIAL_LIVES',
    'SHIP_SHOOT_COOLDOWN',
    # Weapons
    'BULLET_SPEED', 'BULLET_LIFETIME', 'BULLET_DAMAGE',
    'BULLET_COOLDOWN', 'MAX_BULLETS',
    # Asteroids
    'ASTEROID_SIZES', 'ASTEROID_POINTS', 'ASTEROID_RADIUS',
    'ASTEROID_SPEED', 'ASTEROID_SPLIT_COUNT', 'MIN_ASTEROID_COUNT',
    # Particles
    'PARTICLE_COLORS', 'EXPLOSION_PARTICLE_COUNT',
    'EXPLOSION_PARTICLE_LIFETIME', 'EXPLOSION_PARTICLE_SPEED',
    'THRUST_PARTICLE_COUNT', 'THRUST_PARTICLE_LIFETIME',
    'THRUST_PARTICLE_SPEED',
    # Colors
    'BLACK', 'WHITE', 'RED', 'GREEN', 'BLUE', 'YELLOW',
    # Display
    'WINDOW_WIDTH', 'WINDOW_HEIGHT', 'WINDOW_TITLE', 'FPS',
    'LAYER_BACKGROUND', 'LAYER_PARTICLES', 'LAYER_ASTEROIDS',
    'LAYER_BULLETS', 'LAYER_PLAYER', 'LAYER_UI',
    # Game Settings
    'MENU_FONT_SIZE', 'MENU_COLOR', 'MENU_HOVER_COLOR', 'MENU_SPACING',
    'SOUND_VOLUME', 'MUSIC_VOLUME',
    'ASSET_DIR', 'SPRITE_DIR', 'SOUND_DIR', 'MUSIC_DIR', 'FONT_DIR',
    'STARTING_LIVES', 'SCORE_MULTIPLIER', 'HIGH_SCORE_COUNT'
)