"""Game constants."""

# Window dimensions
SCREEN_WIDTH = WINDOW_WIDTH = 800
SCREEN_HEIGHT = WINDOW_HEIGHT = 600
TARGET_FPS = FPS = 60

# Game settings
BACKGROUND_COLOR = (0, 0, 0)
STARTING_LIVES = 3
INITIAL_ASTEROIDS = 4
ASTEROIDS_PER_LEVEL = 2
EXTRA_LIFE_SCORE = 10000

# Ship settings
SHIP_ACCELERATION = 300.0
SHIP_ROTATION_SPEED = 180.0
SHIP_MAX_SPEED = 400.0
SHIP_FRICTION = 0.99
SHIP_INVULNERABILITY_TIME = 3.0

# Physics settings
FRICTION = 0.99
MAX_SPEED = 400.0
ROTATION_SPEED = 180.0
THRUST_FORCE = 300.0
PHYSICS_TIME_STEP = 1.0 / 60.0
PHYSICS_VELOCITY_ITERATIONS = 8
PHYSICS_POSITION_ITERATIONS = 3

# Collision settings
COLLISION_MARGIN = 2  # pixels

# Weapon settings
BULLET_SPEED = 500.0
BULLET_LIFETIME = 1.0
FIRE_RATE = 0.25

# Asteroid settings
ASTEROID_SPEED_MIN = 50.0
ASTEROID_SPEED_MAX = 150.0
ASTEROID_ROTATION_MIN = 45.0
ASTEROID_ROTATION_MAX = 180.0
ASTEROID_SPLIT_SPEED_BOOST = 1.2
ASTEROID_LARGE_SIZE = 40
ASTEROID_MEDIUM_SIZE = 20
ASTEROID_SMALL_SIZE = 10
ASTEROID_LARGE_POINTS = 100
ASTEROID_MEDIUM_POINTS = 50
ASTEROID_SMALL_POINTS = 25

# Scoring
SCORE_LARGE_ASTEROID = 100
SCORE_MEDIUM_ASTEROID = 50
SCORE_SMALL_ASTEROID = 25

# Colors
BLACK = (0, 0, 0)
WHITE = (255, 255, 255)
RED = (255, 0, 0)
GREEN = (0, 255, 0)
BLUE = (0, 0, 255)
YELLOW = (255, 255, 0)

# Debug settings
DEBUG_DRAW_COLLIDERS = False
DEBUG_SHOW_FPS = True

# Level settings
INITIAL_ASTEROIDS = 4
ASTEROIDS_INCREMENT = 2
MAX_ASTEROIDS = 12

# Effect settings
THRUST_EFFECT_LIFETIME = 0.5
EXPLOSION_EFFECT_LIFETIME = 1.0
SPARKLE_EFFECT_LIFETIME = 0.3

# Audio settings
SOUND_VOLUME = 0.7
MUSIC_VOLUME = 0.5

# UI settings
FONT_SIZE_SMALL = 16
FONT_SIZE_MEDIUM = 24
FONT_SIZE_LARGE = 32
UI_PADDING = 10

# Game states
MENU_STATE = "menu"
GAME_STATE = "game"
PAUSE_STATE = "pause"
GAME_OVER_STATE = "game_over"
HIGH_SCORE_STATE = "high_score"

# Achievements
ACHIEVEMENT_FIRST_KILL = "first_kill"
ACHIEVEMENT_SURVIVOR = "survivor"
ACHIEVEMENT_SHARPSHOOTER = "sharpshooter"

# Statistics
STAT_ASTEROIDS_DESTROYED = "asteroids_destroyed"
STAT_BULLETS_FIRED = "bullets_fired"
STAT_DEATHS = "deaths"
STAT_TIME_PLAYED = "time_played"
STAT_HIGH_SCORE = "high_score"

# Resources
RESOURCE_SHIP = "ship"
RESOURCE_ASTEROID = "asteroid"
RESOURCE_BULLET = "bullet"
RESOURCE_EXPLOSION = "explosion"
RESOURCE_THRUST = "thrust"

# Input bindings
INPUT_LEFT = "left"
INPUT_RIGHT = "right"
INPUT_THRUST = "thrust"
INPUT_FIRE = "fire"
INPUT_PAUSE = "pause"

# Events
EVENT_GAME_START = "game_start"
EVENT_GAME_OVER = "game_over"
EVENT_LEVEL_START = "level_start"
EVENT_LEVEL_COMPLETE = "level_complete"
EVENT_PLAYER_HIT = "player_hit"
EVENT_ASTEROID_HIT = "asteroid_hit"
EVENT_SCORE_CHANGED = "score_changed"
EVENT_ACHIEVEMENT_UNLOCKED = "achievement_unlocked" 